services:
  - type: web
    name: club369-backend
    env: python
    buildCommand: "pip install --upgrade pip && pip install -r backend/requirements.txt"
    startCommand: "cd backend && gunicorn cloud369_backend.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: DATABASE_URL
        fromDatabase:
          name: club369-db
          property: connectionString
